name: card_settings_example
description: A Flutter project that demonstrated the use of the card_settings package.
version: 1.0.0 
publish_to: none

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  card_settings:
    path: ../
  font_awesome_flutter:
  adaptive_theme: ^2.0.0
  google_fonts: ^4.0.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <4.0.0"

flutter:
  uses-material-design: true

  assets:
    - assets/twilight_sparkle.png


