name: card_settings_example
description: A Flutter project that demonstrated the use of the card_settings package.
version: 1.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  card_settings:
    path: ../
  font_awesome_flutter: ^8.7.0
  dynamic_theme: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/twilight_sparkle.png
