name: card_settings
description: A flutter package for building card based settings forms. This includes a library of pre-built form field widgets.
version: 3.5.0 
homepage: https://github.com/codegrue/card_settings
issue_tracker: https://github.com/codegrue/card_settings/issues

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: ^0.18.0
  meta: ^1.8.0
  extended_masked_text: ^2.3.1
  flutter_cupertino_settings: ^0.5.0 # show apple style dialogs
  flutter_material_pickers: ^3.5.0 # show android style dialogs
  pattern_formatter: ^3.0.0 # used for localized doubles
  flutter_multi_formatter: ^2.10.4  # used for localized phone numbers

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  mockito: ^5.3.2

environment:
  sdk: ">=2.12.0 <4.0.0"

flutter:
  uses-material-design: true
