name: card_settings
description: A flutter package for building card based settings forms. This includes a library of pre-built form field widgets.
version: 3.0.0
homepage: https://github.com/codegrue/card_settings
issue_tracker: https://github.com/codegrue/card_settings/issues

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  extended_masked_text: ^2.1.0
  intl: ^0.17.0
  meta: ^1.2.4
  flutter_cupertino_settings: ^0.5.0
  flutter_material_pickers: ^3.0.0
  pattern_formatter: ^2.0.0 # used for localized doubles
  flutter_multi_formatter: ^2.0.2 # used for localized phone numbers

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  mockito: ^5.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter:
  uses-material-design: true
