name: card_settings
description: A flutter package for building card based settings forms. This includes a library of pre-built form field widgets.
version: 1.12.2
homepage: https://github.com/codegrue/card_settings

dependencies:
  flutter:
    sdk: flutter
  flutter_masked_text: ^0.8.0
  intl: ^0.16.0
  meta: ^1.1.8
  cupertino_icons: ^0.1.3
  flutter_cupertino_settings: ^0.3.1
  flutter_material_pickers: ^1.7.4
  pattern_formatter: ^1.0.2 # used for localized doubles
  flutter_multi_formatter: ^1.1.6 # used for localized phone numbers

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  mockito:

environment:
  sdk: ">=2.0.0 <3.0.0"

flutter:
  uses-material-design: true
